/*
 * gpu_miner.c - Hybrid CPU+GPU Whive (yespower) miner v2
 *
 * ⚠️ PROTOTYPE / PROOF OF CONCEPT ⚠️
 * This code was generated by an AI agent (Hermes Agent by Nous Research)
 * as an experiment in GPU-accelerated mining. It is NOT production-grade,
 * NOT optimized, and NOT audited. Use at your own risk.
 *
 * Build:
 *   gcc -O3 -o gpu_miner gpu_miner.c \
 *       -Iwhive-cpuminer-ref/yespower \
 *       -lOpenCL -lm \
 *       whive-cpuminer-ref/yespower/yespower-ref.o \
 *       whive-cpuminer-ref/yespower/sha256.o \
 *       -lpthread
 *
 * Configuration: edit the POOL_HOST, POOL_PORT, WALLET, WORKER defines below.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdarg.h>
#include <unistd.h>
#include <pthread.h>
#include <time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <errno.h>
#include <CL/cl.h>
#include "sha256.h"

#define POOL_HOST   "YOUR_POOL_HOST"
#define POOL_PORT   3333
#define WALLET      "YOUR_WALLET_ADDRESS"
#define WORKER      "YOUR_WORKER_NAME"
#define BATCH       64
#define MAXLINE     65536
#define RECONN      5

static int fd=-1,running=1;
static cl_context ctx;static cl_device_id dev;static cl_command_queue q;
static cl_program pr;static cl_kernel kr;
static cl_mem dB,dV,dS;
static uint64_t thashes=0,tacc=0,trej=0;
static time_t t0;
static double pool_diff = 1.0;
static uint8_t share_target[32];

static void logm(const char*f,...){
    va_list a;time_t t=time(NULL);struct tm*tm=localtime(&t);
    fprintf(stderr,"[%02d:%02d:%02d] ",tm->tm_hour,tm->tm_min,tm->tm_sec);
    va_start(a,f);vfprintf(stderr,f,a);va_end(a);fprintf(stderr,"\n");
}

static int tcpcon(){
    struct hostent*h=gethostbyname(POOL_HOST);
    if(!h)return -1;
    struct sockaddr_in a;
    memcpy(&a.sin_addr,h->h_addr_list[0],h->h_length);
    a.sin_family=AF_INET;a.sin_port=htons(POOL_PORT);
    int s=socket(AF_INET,SOCK_STREAM,0);
    if(s<0)return -1;
    struct timeval tv={30,0};
    setsockopt(s,SOL_SOCKET,SO_RCVTIMEO,&tv,sizeof(tv));
    setsockopt(s,SOL_SOCKET,SO_SNDTIMEO,&tv,sizeof(tv));
    if(connect(s,(struct sockaddr*)&a,sizeof(a))<0){close(s);return -1;}
    return s;
}

static int snd(const char*f,...){
    char b[4096];va_list a;
    va_start(a,f);int n=vsnprintf(b,sizeof(b),f,a);va_end(a);
    b[n]='\n';b[n+1]=0;
    return write(fd,b,n+1);
}

static int rcv(char*b,int max){
    int p=0;
    while(p<max-1){
        char c;int n=read(fd,&c,1);
        if(n<=0)return -1;
        if(c=='\n'){b[p]=0;return p;}
        b[p++]=c;
    }
    b[p]=0;return p;
}

/* Extract a value from JSON by key */
static char *jget(const char*j,const char*k,char*v,int sz){
    char s[128];snprintf(s,128,"\"%s\"",k);
    const char*p=strstr(j,s);if(!p)return NULL;
    p=strchr(p,':');if(!p)return NULL;p++;
    while(*p==' '||*p=='\t')p++;
    if(*p=='['){/*array - not supported*/return NULL;}
    if(*p=='"'){p++;int i=0;while(*p&&*p!='"'&&i<sz-1)v[i++]=*p++;v[i]=0;return v;}
    /* number */
    {int i=0;while(*p&&*p!=','&&*p!='}'&&*p!=']'&&i<sz-1)v[i++]=*p++;v[i]=0;return v;}
}

/* Find nth element of JSON array (0-indexed) */
static int jget_arr_elems(const char*j,const char*k,char elems[][256],int max){
    char s[128];snprintf(s,128,"\"%s\"",k);
    const char*p=strstr(j,s);if(!p)return 0;
    p=strchr(p,':');if(!p)return 0;p++;
    while(*p==' ')p++;
    if(*p!='[')return 0;
    p++;int n=0;
    while(*p&&n<max){
        while(*p==' '||*p==',')p++;
        if(*p==']')break;
        if(*p=='"'){
            p++;int i=0;
            while(*p&&*p!='"'){if(i<255)elems[n][i++]=*p;p++;}
            elems[n][i]=0;n++;if(*p)p++;
        }else if(*p=='['){/*skip nested*/int d=1;p++;while(*p&&d){if(*p=='[')d++;if(*p==']')d--;p++;}}
        else{int i=0;while(*p&&*p!=','&&*p!=']'){if(i<255)elems[n][i++]=*p;p++;}elems[n][i]=0;n++;}
    }
    return n;
}

/* Hex bin helpers */
static int h2b(const char*h,uint8_t*b,int bl){
    for(int i=0;i<bl;i++)if(sscanf(h+i*2,"%2hhx",&b[i])!=1)return -1;
    return 0;
}

static void b2h(const uint8_t*b,char*h,int bl){
    for(int i=0;i<bl;i++)sprintf(h+i*2,"%02x",b[i]);
}

static void revb(uint8_t*b,int n){for(int i=0;i<n/2;i++){uint8_t t=b[i];b[i]=b[n-1-i];b[n-1-i]=t;}}

/* Compute share target from difficulty: target = max_target / difficulty (approx) */
static void calc_target(double diff){
    /* max_target = 0x00000000FFFF0000000000000000000000000000000000000000000000000000 */
    memset(share_target,0,32);
    share_target[4]=0xFF;share_target[5]=0xFF;
    if(diff<=0)diff=1;
    pool_diff=diff;
    /* Divide first 8 bytes (big-endian) by diff as a 64-bit quantity */
    uint64_t top=((uint64_t)share_target[4]<<56)|((uint64_t)share_target[5]<<48)|
                 ((uint64_t)share_target[6]<<40)|((uint64_t)share_target[7]<<32);
    top=(uint64_t)((double)top/diff);
    share_target[4]=(top>>56)&0xff;
    share_target[5]=(top>>48)&0xff;
    share_target[6]=(top>>40)&0xff;
    share_target[7]=(top>>32)&0xff;
    share_target[8]=(top>>24)&0xff;
    share_target[9]=(top>>16)&0xff;
    share_target[10]=(top>>8)&0xff;
    share_target[11]=top&0xff;
}

/* Check if hash meets share target (256-bit big-endian comparison) */
static int meets_target(const uint8_t*h){
    for(int i=0;i<32;i++){
        if(h[i]<share_target[i])return 1;
        if(h[i]>share_target[i])return 0;
    }
    return 1;
}

/* SHA256(SHA256(x)) */
static void sha256d(const uint8_t*x,uint8_t*d){
    uint8_t m[32];SHA256_Buf(x,80,m);
    SHA256_Buf(m,32,d);
}

/* ===== GPU ===== */
#define CK(e)do{cl_int _e=(e);if(_e){logm("CL err %d",_e);exit(1);}}while(0)
static void gpu_init(){
    cl_platform_id p;cl_int e;
    CK(clGetPlatformIDs(1,&p,NULL));
    CK(clGetDeviceIDs(p,CL_DEVICE_TYPE_GPU,1,&dev,NULL));
    char nm[128];clGetDeviceInfo(dev,CL_DEVICE_NAME,sizeof(nm),nm,NULL);
    logm("GPU: %s",nm);
    ctx=clCreateContext(NULL,1,&dev,NULL,NULL,&e);CK(e);
    q=clCreateCommandQueue(ctx,dev,0,&e);CK(e);
    FILE*f=fopen("yespower_smix.cl","rb");if(!f){logm("Missing yespower_smix.cl");exit(1);}
    fseek(f,0,SEEK_END);long fs=ftell(f);rewind(f);
    char*s=malloc(fs+1);fread(s,1,fs,f);s[fs]=0;fclose(f);
    const char*ss[]={s};
    pr=clCreateProgramWithSource(ctx,1,ss,NULL,&e);CK(e);
    e=clBuildProgram(pr,1,&dev,"-cl-std=CL3.0",NULL,NULL);
    if(e){char lg[16384];clGetProgramBuildInfo(pr,dev,CL_PROGRAM_BUILD_LOG,sizeof(lg),lg,NULL);logm("Build:\n%s",lg);exit(1);}
    free(s);logm("Kernel built");
    kr=clCreateKernel(pr,"yespower_smix",&e);CK(e);
    dB=clCreateBuffer(ctx,CL_MEM_READ_WRITE,BATCH*4096,NULL,&e);CK(e);
    dV=clCreateBuffer(ctx,CL_MEM_READ_WRITE,BATCH*2048*1024*4,NULL,&e);CK(e);
    dS=clCreateBuffer(ctx,CL_MEM_READ_WRITE,BATCH*3*8192*4,NULL,&e);CK(e);
    logm("GPU ready, batch=%d",BATCH);
}

static void gpu_run(uint8_t*bi,int n){
    CK(clEnqueueWriteBuffer(q,dB,CL_TRUE,0,n*4096,bi,0,NULL,NULL));
    uint32_t wg=0,nw=n;
    clSetKernelArg(kr,0,sizeof(cl_mem),&dB);
    clSetKernelArg(kr,1,sizeof(cl_mem),&dV);
    clSetKernelArg(kr,2,sizeof(cl_mem),&dS);
    clSetKernelArg(kr,3,sizeof(uint32_t),&wg);
    clSetKernelArg(kr,4,sizeof(uint32_t),&nw);
    size_t gs=n;CK(clEnqueueNDRangeKernel(q,kr,1,NULL,&gs,NULL,0,NULL,NULL));
    clFinish(q);
    CK(clEnqueueReadBuffer(q,dB,CL_TRUE,0,n*4096,bi,0,NULL,NULL));
}

/* ===== Merkle root ===== */
static void build_coinbase(const char*cb1,const char*cb2,
                           const char*en1,const char*en2,
                           uint8_t*cb,int*cbl){
    uint8_t b1[1024],b2[1024],e1[256];
    int l1=strlen(cb1)/2,l2=strlen(cb2)/2,le1=strlen(en1)/2;
    h2b(cb1,b1,l1);h2b(cb2,b2,l2);h2b(en1,e1,le1);
    uint8_t en2b[4]={0};
    int le2=strlen(en2)/2;if(le2>4)le2=4;
    h2b(en2,en2b,le2);
    memcpy(cb,b1,l1);memcpy(cb+l1,e1,le1);
    memcpy(cb+l1+le1,en2b,le2);memcpy(cb+l1+le1+le2,b2,l2);
    *cbl=l1+le1+le2+l2;
}

static void compute_merkle(const char*cb1,const char*cb2,
                         const char*en1,const char*en2,
                         const char*merkle_hex[],int n_merkle,
                         uint8_t root[32]){
    uint8_t cb[2048];int cbl;
    build_coinbase(cb1,cb2,en1,en2,cb,&cbl);
    SHA256_Buf(cb,cbl,root);
    SHA256_Buf(root,32,root);
    for(int i=0;i<n_merkle;i++){
        uint8_t branch[32];h2b(merkle_hex[i],branch,32);
        uint8_t buf[64];
        memcpy(buf,root,32);
        memcpy(buf+32,branch,32);
        /* Reverse endianness for merkle */
        revb(buf,32);revb(buf+32,32);
        SHA256_Buf(buf,64,root);
        SHA256_Buf(root,32,root);
    }
}

/* ===== Header building ===== */
static void build_header(uint8_t*hdr,uint32_t nonce,
                          const uint8_t merkle[32]){
    memset(hdr,0,80);
    hdr[0]=0x20; /* version 0x20000000 LE */
    memcpy(hdr+4,&nonce,4); /* placeholder - wrong, FIXME */
    /* Proper header would go here */
}

/* ===== Main ===== */
static void *stats(void*a){(void)a;
    while(running){sleep(30);time_t e=time(NULL)-t0;
        if(e>0)logm("Stats: %.0f H/s total=%lu acc=%lu rej=%lu",
                    (double)thashes/e,thashes,tacc,trej);}
    return NULL;
}

int main(){
    logm("=== Whive GPU Miner ===");
    logm("Pool: %s:%d Wallet: %s/%s",POOL_HOST,POOL_PORT,WALLET,WORKER);
    gpu_init();
    pthread_t st;pthread_create(&st,NULL,stats,NULL);
    t0=time(NULL);
    uint8_t*bb=malloc(BATCH*4096);
    uint8_t(*keys)[32]=malloc(BATCH*32);
    uint32_t*nonces=malloc(BATCH*4);
    uint8_t merkle_root[32]={0};
    char line[MAXLINE],en1[64]="",jobid[128]="",
         prevh[128]="",cb1[1024]="",cb2[1024]="",
         mroots[10][256],ver[16],nbits[16],ntime[16];
    int nmroot=0,got_job=0;

    while(running){
        if(fd>=0)close(fd);
        fd=tcpcon();
        if(fd<0){logm("Connection failed, retry in %ds",RECONN);sleep(RECONN);continue;}
        logm("Connected");
        
        /* Subscribe */
        snd("{\"id\":1,\"method\":\"mining.subscribe\",\"params\":[\"%s/1.0.0\"]}",WORKER);
        if(rcv(line,sizeof(line))<0){sleep(RECONN);continue;}
        
        /* Parse subscribe result for extranonce1 and extranonce2_size */
        {
            char result_val[MAXLINE]="";
            /* Find result array and extract elements */
            const char*rp=strstr(line,"\"result\"");
            if(rp){
                rp=strchr(rp,':');
                if(rp){
                    rp++;
                    while(*rp==' ')rp++;
                    if(*rp=='[')rp++;
                    /* Skip subscription details (nested array) */
                    if(*rp=='['){int d=1;rp++;while(*rp&&d){if(*rp=='[')d++;if(*rp==']')d--;rp++;}}
                    while(*rp&&(*rp==','||*rp==' '))rp++;
                    /* extranonce1 */
                    if(*rp=='"'){rp++;int i=0;while(*rp&&*rp!='"')en1[i++]=*rp++;en1[i]=0;rp++;}
                    while(*rp&&(*rp==','||*rp==' '))rp++;
                    /* extranonce2_size */
                    {int i=0;while(*rp&&*rp!=','&&*rp!=']'&&i<63)result_val[i++]=*rp++;result_val[i]=0;}
                    logm("Subscribe: en1=%s en2sz=%s",en1,result_val);
                }
            }
        }
        
        /* Authorize - keep reading until we get id:2 response */
        snd("{\"id\":2,\"method\":\"mining.authorize\",\"params\":[\"%s\",\"\"]}",WALLET);
        int auth_ok=0;
        while(running&&fd>=0){
            if(rcv(line,sizeof(line))<0)break;
            if(strstr(line,"\"id\":2")){
                auth_ok=(strstr(line,"true")!=NULL);
                break;
            }
            /* Handle interleaved messages */
            if(strstr(line,"\"mining.set_difficulty\"")){
                char v[64];jget(line,"params",v,sizeof(v));
                logm("Difficulty: %s",v);
                double d0=atof(v);calc_target(d0);
            }else if(strstr(line,"\"mining.notify\"")){
                /* Will be handled in main loop */
            }
        }
        logm("Authorize: %s",auth_ok?"OK":"FAIL");
        if(!auth_ok){sleep(RECONN);continue;}
        
        /* Now listen for jobs */
        got_job=0;
        uint32_t ns=0;
        
        while(running&&fd>=0){
            if(rcv(line,sizeof(line))<0){logm("Disconnected");break;}
            
            if(strstr(line,"\"mining.notify\"")){
                /* Parse job params */
                const char*p=strstr(line,"\"params\"");
                if(!p){logm("Bad notify");continue;}
                p=strchr(p,'[');if(!p)continue;p++;
                
                /* Job ID */
                while(*p=='"')p++;int i=0;while(*p&&*p!='"')jobid[i++]=*p++;jobid[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* prevhash */
                while(*p=='"')p++;i=0;while(*p&&*p!='"')prevh[i++]=*p++;prevh[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* coinb1 */
                while(*p=='"')p++;i=0;while(*p&&*p!='"')cb1[i++]=*p++;cb1[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* coinb2 */
                while(*p=='"')p++;i=0;while(*p&&*p!='"')cb2[i++]=*p++;cb2[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* Merkle branches array */
                nmroot=0;
                if(*p=='['){
                    p++;
                    while(*p&&*p!=']'&&nmroot<10){
                        while(*p==' '||*p==',')p++;
                        if(*p=='"'){p++;i=0;while(*p&&*p!='"')mroots[nmroot][i++]=*p++;mroots[nmroot][i]=0;nmroot++;p++;}
                    }
                    if(*p==']')p++;
                }
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* version */
                while(*p=='"')p++;i=0;while(*p&&*p!='"')ver[i++]=*p++;ver[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* nbits */
                while(*p=='"')p++;i=0;while(*p&&*p!='"')nbits[i++]=*p++;nbits[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;while(*p==' ')p++;
                
                /* ntime */
                while(*p=='"')p++;i=0;while(*p&&*p!='"')ntime[i++]=*p++;ntime[i]=0;
                while(*p&&*p!=',')p++;if(*p==',')p++;
                
                int clean=(*p=='t'||*p=='1');
                logm("Job %s: ver=%s bits=%s time=%s clean=%d mroots=%d",
                     jobid,ver,nbits,ntime,clean,nmroot);
                
                if(clean)ns=0;
                got_job=1;
                char en2[16];
                
                /* Mine this job */
                int limit=50000;
                int bi=0;
                for(uint32_t n=ns;n<ns+limit&&running;n++){
                    /* Build header with this nonce */
                    uint8_t hdr[80];uint8_t merk[32];
                    snprintf(en2,16,"%08x",(unsigned)(n/1000000));
                    
                    {
                        const char *mptrs[10];
                        for(int mi=0;mi<nmroot&&mi<10;mi++)mptrs[mi]=mroots[mi];
                        compute_merkle(cb1,cb2,en1,en2,mptrs,nmroot,merk);
                    }
                    
                    /* Build header: version(4) LE + prevhash(32) LE + merkle(32) LE + ntime(4) LE + nbits(4) LE + nonce(4) LE */
                    memset(hdr,0,80);
                    uint32_t v;sscanf(ver,"%x",&v);
                    hdr[0]=v&0xff;hdr[1]=(v>>8)&0xff;hdr[2]=(v>>16)&0xff;hdr[3]=(v>>24)&0xff;
                    uint8_t pv[32];h2b(prevh,pv,32);
                    for(int j=0;j<32;j++)hdr[4+j]=pv[31-j]; /* prevhash as LE */
                    revb(merk,32); /* merkle root LE */
                    memcpy(hdr+36,merk,32);
                    uint32_t tm;sscanf(ntime,"%x",&tm);
                    hdr[68]=tm&0xff;hdr[69]=(tm>>8)&0xff;hdr[70]=(tm>>16)&0xff;hdr[71]=(tm>>24)&0xff;
                    uint32_t bt;sscanf(nbits,"%x",&bt);
                    hdr[72]=bt&0xff;hdr[73]=(bt>>8)&0xff;hdr[74]=(bt>>16)&0xff;hdr[75]=(bt>>24)&0xff;
                    hdr[76]=n&0xff;hdr[77]=(n>>8)&0xff;hdr[78]=(n>>16)&0xff;hdr[79]=(n>>24)&0xff;
                    
                    uint8_t s[32];SHA256_Buf(hdr,80,s);
                    PBKDF2_SHA256(s,32,NULL,0,1,bb+bi*4096,4096);
                    memcpy(keys[bi],bb+bi*4096,32);
                    nonces[bi]=n;bi++;
                    
                    if(bi>=BATCH){
                        gpu_run(bb,bi);
                        for(int j=0;j<bi;j++){
                            uint8_t res[32];
                            HMAC_SHA256_Buf(bb+j*4096+4096-64,64,keys[j],32,res);
                            thashes++;
                            /* Check target (diff 0.5) */
                            /* Target: first 4 bytes of hash (BE) should be 0x00 or lower */
                            uint32_t hb=((uint32_t)res[31]<<24)|((uint32_t)res[30]<<16)|((uint32_t)res[29]<<8)|res[28];
                            if(meets_target(res)){
                                char nh[16];snprintf(nh,16,"%08x",nonces[j]);
                                char hex[64];b2h(res,hex,32);
                                logm("Share candidate! nonce=%s hash=%s",nh,hex);
                                snd("{\"id\":-1,\"method\":\"mining.submit\",\"params\":[\"%s\",\"%s\",\"%s\",\"%s\",\"%s\"]}",
                                    WALLET,jobid,en2,ntime,nh);
                                tacc++;
                            }
                        }
                        bi=0;ns=n+1;
                    }
                }
                if(bi>0){
                    gpu_run(bb,bi);thashes+=bi;
                    for(int j=0;j<bi;j++){
                        uint8_t res[32];
                        HMAC_SHA256_Buf(bb+j*4096+4096-64,64,keys[j],32,res);
                        uint32_t hb=((uint32_t)res[31]<<24)|((uint32_t)res[30]<<16)|((uint32_t)res[29]<<8)|res[28];
                        if(meets_target(res)){
                            char nh[16];snprintf(nh,16,"%08x",nonces[j]);
                            snd("{\"id\":-1,\"method\":\"mining.submit\",\"params\":[\"%s\",\"%s\",\"%s\",\"%s\",\"%s\"]}",
                                WALLET,jobid,en2,ntime,nh);
                            tacc++;
                        }
                    }
                }
                ns+=limit;
                
            }else if(strstr(line,"\"mining.set_difficulty\"")){
                char v[64];jget(line,"params",v,sizeof(v));
                double d=atof(v);calc_target(d);logm("Difficulty set to %.1f",d);
            }else if(strstr(line,"\"result\":true")&&strstr(line,"\"id\":-1")){
                tacc++;logm("Share accepted");
            }else if(strstr(line,"\"result\":")){
                /* ignore other results */
            }
        }
    }
    free(bb);free(keys);free(nonces);
    return 0;
}
